on:
    push:
        branches:
            - "master"
    schedule:
        - cron: '10 * * * *'

jobs:
    docker-alpine:
        runs-on: ubuntu-22.04
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3
            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            - 
                name: Build and push alpine:unstable
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    tags: k0d3r1s/alpine:unstable
                    platforms: linux/amd64
    docker-alpine-curl:
        runs-on: self-hosted
        needs: docker-alpine
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3
            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push alpine:unstable-curl
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: Dockerfile.curl
                    push: true
                    tags: k0d3r1s/alpine:unstable-curl
                    platforms: linux/amd64
    docker-alpine-action:
        runs-on: ubuntu-22.04
        needs: docker-alpine
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3
            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push alpine:unstable-curl
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: Dockerfile.action
                    push: true
                    tags: k0d3r1s/alpine:action-split
                    platforms: linux/amd64
